# Generated by Django 2.1.2 on 2019-06-29 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(max_length=50)),
                ('starting_date', models.DateTimeField(auto_now_add=True)),
                ('ending_date', models.DateTimeField(auto_now_add=True)),
                ('remark', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=15)),
                ('course_name', models.CharField(max_length=50)),
                ('course_aliases', models.CharField(max_length=30)),
                ('approved_date', models.DateTimeField(auto_now_add=True)),
                ('exam_pattern', models.CharField(choices=[('sem', 'SEMESTER'), ('yr', 'YEARLY'), ('tr', 'TRIMESTER')], default='SEMESTER', max_length=3)),
                ('affiliated_body', models.CharField(max_length=30)),
                ('remark', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=20)),
                ('remark', models.TextField()),
                ('batch_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursemanagement.Batch')),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursemanagement.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='section',
            name='stream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursemanagement.Stream'),
        ),
        migrations.AddField(
            model_name='course',
            name='stream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursemanagement.Stream'),
        ),
        migrations.AddField(
            model_name='batch',
            name='course_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursemanagement.Course'),
        ),
        migrations.AddField(
            model_name='batch',
            name='stream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursemanagement.Stream'),
        ),
    ]
