# Generated by Django 2.1.2 on 2019-07-03 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursemanagement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feesmanagement',
            name='discount_amount',
        ),
    ]
