# Generated by Django 2.1.2 on 2019-06-29 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursemanagement', '0002_auto_20190629_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='ending_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='batch',
            name='starting_date',
            field=models.DateTimeField(),
        ),
    ]
