# Generated by Django 2.1.2 on 2019-07-03 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coursemanagement', '0002_remove_feesmanagement_discount_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeesManagementSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursemanagement.Batch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursemanagement.Course')),
                ('fees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursemanagement.FeesManagement')),
            ],
        ),
    ]
