# Generated by Django 2.1.2 on 2019-07-03 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursemanagement', '0003_feesmanagementsetting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feesmanagementsetting',
            name='fees',
        ),
        migrations.AddField(
            model_name='feesmanagementsetting',
            name='fees',
            field=models.ManyToManyField(to='coursemanagement.FeesManagement'),
        ),
    ]
