# Generated by Django 2.1.2 on 2019-06-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursemanagement', '0003_auto_20190629_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], default='4', max_length=1),
        ),
        migrations.AddField(
            model_name='course',
            name='syllabus',
            field=models.FileField(default='myfile.pdf', upload_to=''),
            preserve_default=False,
        ),
    ]
