# Generated by Django 2.1.2 on 2019-07-09 05:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursemanagement', '0004_auto_20190703_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='feesmanagement',
            name='sanctioned_amount',
            field=models.IntegerField(blank=True, default=10000, validators=[django.core.validators.MaxValueValidator(9999999)]),
            preserve_default=False,
        ),
    ]
