# Generated by Django 2.1.2 on 2019-07-02 07:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coursemanagement', '0004_auto_20190629_1836'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeesManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_type', models.IntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(10000000)])),
                ('actual_amount', models.IntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(9999999)])),
                ('discount_amount', models.IntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(9999999)])),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='fees',
            field=models.ForeignKey(default=100000, on_delete=django.db.models.deletion.CASCADE, to='coursemanagement.FeesManagement'),
            preserve_default=False,
        ),
    ]
