# Generated by Django 2.1.2 on 2019-07-02 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursemanagement', '0005_auto_20190702_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feesmanagement',
            name='fee_type',
            field=models.CharField(max_length=20),
        ),
    ]
