# Generated by Django 2.1.2 on 2019-07-11 05:44

import coursemanagement.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursemanagement', '0005_feesmanagement_sanctioned_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='total_seats',
            field=models.IntegerField(default=30, validators=[coursemanagement.models.MaxLengthIntegerValidator(3)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feesmanagement',
            name='actual_amount',
            field=models.IntegerField(blank=True, validators=[coursemanagement.models.MaxLengthIntegerValidator(4)]),
        ),
        migrations.AlterField(
            model_name='feesmanagement',
            name='sanctioned_amount',
            field=models.IntegerField(blank=True, validators=[coursemanagement.models.MaxLengthIntegerValidator(4)]),
        ),
    ]
