# Generated by Django 2.1.2 on 2019-07-15 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursemanagement', '0006_auto_20190711_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feesmanagement',
            name='actual_amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='feesmanagement',
            name='sanctioned_amount',
            field=models.IntegerField(blank=True),
        ),
    ]
