# Generated by Django 2.1.2 on 2019-07-02 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursemanagement', '0006_auto_20190702_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='fees',
        ),
        migrations.AddField(
            model_name='course',
            name='fees',
            field=models.ManyToManyField(to='coursemanagement.FeesManagement'),
        ),
    ]
