# Generated by Django 2.1.2 on 2019-07-15 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursemanagement', '0007_auto_20190715_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feesmanagement',
            name='sanctioned_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
