# Generated by Django 2.1.2 on 2019-07-02 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursemanagement', '0007_auto_20190702_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='fees',
        ),
    ]
