# Generated by Django 2.1.2 on 2019-07-15 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursemanagement', '0008_auto_20190715_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='total_seats',
            field=models.IntegerField(),
        ),
    ]
