# Generated by Django 2.1.2 on 2019-07-15 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursemanagement', '0009_auto_20190715_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feestype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='FeesManagement',
        ),
        migrations.AlterField(
            model_name='feesmanagementsetting',
            name='fees',
            field=models.ManyToManyField(to='coursemanagement.Feestype'),
        ),
    ]
