# Generated by Django 2.1.2 on 2019-07-15 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursemanagement', '0010_auto_20190715_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feestype',
            name='fee_type',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
