# Generated by Django 2.1.2 on 2019-07-17 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursemanagement', '0012_feesmanagementsetting_stream'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='short_name',
            field=models.CharField(default='Me', max_length=4),
            preserve_default=False,
        ),
    ]
