# Generated by Django 2.1.2 on 2019-07-16 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coursemanagement', '0012_feesmanagementsetting_stream'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeesPlanType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fees_type', models.CharField(max_length=10)),
                ('actual_fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursemanagement.Batch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursemanagement.Course')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursemanagement.Stream')),
            ],
        ),
    ]
