# Generated by Django 2.1.2 on 2019-08-06 05:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '__first__'),
        ('coursemanagement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApproveFeeplanType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approve_fees', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('no_of_installments', models.IntegerField(blank=True, null=True)),
                ('first_installment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('due_date_first_installment', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('second_installment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('due_date_second_installment', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('third_installment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('due_date_third_installment', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursemanagement.Batch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursemanagement.Course')),
            ],
        ),
        migrations.CreateModel(
            name='FeeCollect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.IntegerField(default=1)),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amount_left', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('is_active', models.BooleanField(default=True)),
                ('approve_fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeplan.ApproveFeeplanType')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
        ),
        migrations.CreateModel(
            name='FeeDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pay_date', models.DateField(default=datetime.date.today)),
                ('is_active', models.BooleanField(default=True)),
                ('fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeplan.FeeCollect')),
            ],
        ),
        migrations.CreateModel(
            name='FeesPlanType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('default_installment', models.IntegerField(default=1)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursemanagement.Batch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursemanagement.Course')),
                ('fees_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursemanagement.Feestype')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursemanagement.Stream')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('note_type', models.IntegerField(default=1)),
                ('is_pin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('student_admission_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.Student')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='approvefeeplantype',
            name='fees_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeplan.FeesPlanType'),
        ),
        migrations.AddField(
            model_name='approvefeeplantype',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.Student'),
        ),
    ]
