# Generated by Django 2.1.2 on 2019-07-16 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20190716_1103'),
        ('coursemanagement', '0012_feesmanagementsetting_stream'),
        ('feeplan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApproveFeeplanType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursemanagement.Batch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursemanagement.Course')),
                ('enrollment_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Enrollment')),
                ('fees_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeplan.FeesPlanType')),
            ],
        ),
    ]
