# Generated by Django 2.1.2 on 2019-07-16 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeplan', '0002_approvefeeplantype'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvefeeplantype',
            name='approve_fees',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
