# Generated by Django 2.1.2 on 2019-07-18 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeplan', '0003_approvefeeplantype_approve_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='feesplantype',
            name='default_installment',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=12),
        ),
    ]
