# Generated by Django 2.1.2 on 2019-07-18 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeplan', '0005_auto_20190718_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feesplantype',
            name='default_installment',
            field=models.IntegerField(default=1),
        ),
    ]
