# Generated by Django 2.1.2 on 2019-07-18 11:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeplan', '0006_auto_20190718_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvefeeplantype',
            name='due_date_first_installment',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AddField(
            model_name='approvefeeplantype',
            name='due_date_second_installment',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AddField(
            model_name='approvefeeplantype',
            name='due_date_third_installment',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AddField(
            model_name='approvefeeplantype',
            name='first_installment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='approvefeeplantype',
            name='no_of_installments',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='approvefeeplantype',
            name='second_installment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='approvefeeplantype',
            name='third_installment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
