# Generated by Django 2.1.2 on 2019-07-22 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeplan', '0007_auto_20190718_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvefeeplantype',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
