# Generated by Django 2.1.2 on 2019-07-22 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeplan', '0008_approvefeeplantype_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvefeeplantype',
            name='approve_fees',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
