# Generated by Django 2.1.2 on 2019-06-21 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=30)),
                ('department_name', models.CharField(max_length=50)),
                ('course_aliases', models.CharField(max_length=30)),
                ('duration', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=2, max_length=1)),
                ('no_of_semestars', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=4, max_length=1)),
                ('approved_university', models.CharField(max_length=30)),
                ('syllabus', models.FileField(blank=True, upload_to='course/syllabus/')),
                ('remarks', models.TextField()),
            ],
        ),
    ]
