# Generated by Django 2.1.2 on 2019-06-24 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_remove_course_syllabus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='name',
            new_name='department',
        ),
    ]
