# Generated by Django 2.1.2 on 2019-07-22 12:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('mr', 'Mr.'), ('ms', 'Mrs.'), ('miss', 'Miss'), ('dr', 'Dr.')], default='Mr.', max_length=5)),
                ('first_name', models.CharField(max_length=15)),
                ('middle_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('date_of_birth', models.DateTimeField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'others')], default='Male', max_length=10)),
                ('fathers_name', models.CharField(max_length=40)),
                ('mothers_name', models.CharField(max_length=40)),
                ('phone_no', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[0-9]{10}$', message='Phone Number must be of 12 Digits')])),
                ('aadhar_no', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator('^[0-9]{12}$', message='Aadhar Number must be of 12 Digits')])),
                ('pan_no', models.CharField(max_length=15)),
                ('epfo_no', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('nationality', models.CharField(choices=[('in', 'Indian')], max_length=10)),
                ('caste', models.CharField(choices=[('Gen', 'GEN'), ('sc', 'SC'), ('st', 'ST'), ('obc', 'OBC'), ('others', 'Others')], default='Others', max_length=5)),
                ('religion', models.CharField(choices=[('H', 'Hindu'), ('M', 'Muslim'), ('C', 'Christian'), ('O', 'Others')], default='Hindu', max_length=20)),
                ('scale_of_pay', models.CharField(choices=[('5th', '5th Pay'), ('6th', '6th Pay'), ('cons', 'Consolidated')], default=20, max_length=15)),
                ('type_of_joining', models.CharField(choices=[('part', 'Part Time'), ('full', 'Full Time'), ('part', 'Contracted')], default='Full Time', max_length=15)),
                ('communication_address', models.TextField()),
                ('communication_lane_address', models.CharField(max_length=70)),
                ('landmark', models.CharField(max_length=70)),
                ('pin', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^[0-9]{6}$', message='')])),
                ('city', models.CharField(max_length=30)),
                ('district', models.CharField(max_length=25)),
                ('state', models.CharField(max_length=25)),
                ('country', models.CharField(max_length=25)),
                ('bank_name', models.CharField(blank=True, max_length=25)),
                ('bank_account_number', models.IntegerField()),
                ('bank_ifsc_code', models.CharField(blank=True, max_length=25)),
                ('bank_branch', models.CharField(blank=True, max_length=25)),
                ('tenth_subjects', models.CharField(max_length=20)),
                ('tenth_school', models.CharField(max_length=20)),
                ('tenth_board', models.CharField(max_length=20)),
                ('tenth_full_mark', models.IntegerField()),
                ('tenth_secured_mark', models.IntegerField()),
                ('tenth_percentage', models.FloatField()),
                ('twelth_stream', models.CharField(max_length=20)),
                ('twelth_college', models.CharField(max_length=20)),
                ('twelth_board', models.CharField(max_length=20)),
                ('twelth_full_mark', models.IntegerField()),
                ('twelth_secured_mark', models.IntegerField()),
                ('tewlth_percentage', models.FloatField()),
                ('degree_stream', models.CharField(max_length=20)),
                ('degree_college', models.CharField(max_length=20)),
                ('degree_university', models.CharField(max_length=20)),
                ('degree_full_mark', models.IntegerField(blank=True, null=True)),
                ('degree_secured_mark', models.IntegerField(blank=True, null=True)),
                ('degree_percentage', models.FloatField()),
                ('postdegree_stream', models.CharField(blank=True, max_length=20)),
                ('postdegree_college', models.CharField(blank=True, max_length=20)),
                ('postdegree_university', models.CharField(blank=True, max_length=20)),
                ('postdegree_full_mark', models.IntegerField(blank=True, null=True)),
                ('postdegree_secured_mark', models.IntegerField(blank=True, null=True)),
                ('postdegree_percentage', models.FloatField(blank=True, null=True)),
                ('teaching_experience', models.IntegerField()),
                ('industry_experience', models.IntegerField()),
                ('experience_details', models.TextField(blank=True)),
                ('last_appointment_type', models.CharField(choices=[('part', 'Part Time'), ('full', 'Full Time'), ('part', 'Contracted')], default='Full Time', max_length=20)),
                ('last_payment_scale', models.CharField(choices=[('5th', '5th Pay'), ('6th', '6th Pay'), ('cons', 'Consolidated')], default='5th pay', max_length=20)),
                ('other_qualifiaction', models.CharField(blank=True, max_length=15)),
                ('area_of_specialization', models.CharField(max_length=50)),
                ('ug_degree', models.CharField(choices=[('b.tech', 'B.Tech'), ('bachlr', 'Bachelors'), ('be', 'BE')], default='B.Tech', max_length=30)),
                ('pg_degree', models.CharField(choices=[('m.tech', 'M.Tech'), ('master', 'Masters'), ('me', 'ME')], default='M.Tech', max_length=25)),
                ('patents_issued', models.IntegerField(blank=True)),
                ('no_of_pg_projects', models.IntegerField(blank=True)),
                ('physically_handicaped', models.CharField(choices=[('y', 'Yes'), ('n', 'No')], max_length=1)),
                ('national_journal_no', models.IntegerField(blank=True)),
                ('international_journal_no', models.IntegerField(blank=True)),
                ('journal_details', models.TextField(blank=True)),
                ('national_conference_no', models.IntegerField(blank=True)),
                ('international_conference_no', models.IntegerField(blank=True)),
                ('conference_details', models.TextField(blank=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee_Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_department', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee_Designation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_designation', models.CharField(max_length=150)),
                ('employee_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.Category')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.Employee_Department'),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_designation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.Employee_Designation'),
        ),
    ]
