# Generated by Django 2.1.2 on 2019-06-21 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentDetail',
            new_name='StudentDetailForm',
        ),
    ]
