# Generated by Django 2.1.2 on 2019-06-21 07:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20190621_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fathers_name', models.CharField(max_length=20)),
                ('fathers_occupation', models.CharField(choices=[('Govt. Employee', 'Govt. Employee'), ('Private Employee', 'Private Employee'), ('Self Employed', 'Self Employed'), ('Businessman', 'Businessman'), ('Others', 'Others')], default='Others', max_length=30)),
                ('fathers_date_of_birth', models.DateField()),
                ('fathers_phone_no', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[0-9]{10}$', message='Please Enter a Valid Phone Number')])),
                ('fathers_email_id', models.EmailField(max_length=254)),
                ('fathers_annual_income', models.CharField(max_length=10)),
                ('mothers_name', models.CharField(max_length=20)),
                ('mothers_occupation', models.CharField(choices=[('Govt. Employee', 'Govt. Employee'), ('Private Employee', 'Private Employee'), ('Self Employed', 'Self Employed'), ('Businessman', 'Businessman'), ('Home Maker', 'Home Maker'), ('Others', 'Others')], default='Others', max_length=30)),
                ('mothers_date_of_birth', models.DateField()),
                ('mothers_phone_no', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[0-9]{10}$', message='Please Enter a Valid Phone Number')])),
                ('mothers_email_id', models.EmailField(max_length=254)),
                ('mothers_annual_income', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SAF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateTimeField(auto_now_add=True)),
                ('admission_no', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[0-9]{10}$', message='Please Enter Correct Data')])),
                ('admission_date', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Branch')),
                ('parent_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.ParentDetails')),
            ],
        ),
        migrations.CreateModel(
            name='StudentDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('blood_group', models.CharField(choices=[('A+ve', 'A+ve'), ('A-ve', 'A-ve'), ('B+ve', 'B+ve'), ('B-ve', 'B-ve'), ('AB+ve', 'AB+ve'), ('AB-ve', 'AB-ve'), ('O+ve', 'O+ve'), ('O-ve', 'O-ve')], default='O+ve', max_length=5)),
                ('caste', models.CharField(choices=[('Gen', 'GEN'), ('SC', 'SC'), ('ST', 'ST'), ('OBC', 'OBC'), ('Others', 'Others')], default='Others', max_length=5)),
                ('sub_caste', models.CharField(choices=[('Gen', 'GEN'), ('SC', 'SC'), ('ST', 'ST'), ('OBC', 'OBC'), ('Others', 'Others')], default='Others', max_length=5)),
                ('place_of_birth', models.CharField(max_length=20)),
                ('aadhar_number', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator('^[0-9]{12}$', message='Aadhar Number must be of 12 Digits')])),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='StudentDetailForm',
        ),
        migrations.AddField(
            model_name='saf',
            name='student_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.StudentDetail'),
        ),
    ]
