# Generated by Django 2.1.2 on 2019-07-15 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20190715_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='student_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.Student'),
        ),
    ]
