# Generated by Django 2.1.2 on 2019-06-21 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20190621_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentdetails',
            name='mothers_occupation',
            field=models.CharField(choices=[('Govt. Employee', 'Govt. Employee'), ('Private Employee', 'Private Employee'), ('Self Employed', 'Self Employed'), ('Businessman', 'Businesswoman'), ('Home Maker', 'Home Maker'), ('Others', 'Others')], default='Others', max_length=30),
        ),
    ]
