# Generated by Django 2.1.2 on 2019-06-21 09:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20190621_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.CharField(max_length=20)),
                ('stream', models.CharField(max_length=20)),
                ('school', models.CharField(max_length=20)),
                ('university', models.CharField(max_length=20)),
                ('full_mark', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^[0-9]{4}$', message='Please Enter Correct Data')])),
                ('secured_mark', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^[0-9]{4}$', message='Please Enter Correct Data')])),
                ('percentage', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='parentdetails',
            name='mothers_annual_income',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='parentdetails',
            name='mothers_date_of_birth',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='parentdetails',
            name='mothers_email_id',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
