# Generated by Django 2.1.2 on 2019-07-17 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20190717_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='date_of_admission',
            field=models.DateField(blank=True, default='2019-09-06', null=True),
        ),
    ]
