# Generated by Django 2.1.2 on 2019-06-21 09:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20190621_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenth',
            name='full_mark',
            field=models.IntegerField(max_length=4, validators=[django.core.validators.RegexValidator('^[0-9]{4}$', message='Please Enter Correct Data')]),
        ),
        migrations.AlterField(
            model_name='tenth',
            name='percentage',
            field=models.FloatField(max_length=4, verbose_name='percentage'),
        ),
        migrations.AlterField(
            model_name='tenth',
            name='secured_mark',
            field=models.IntegerField(max_length=4, validators=[django.core.validators.RegexValidator('^[0-9]{4}$', message='Please Enter Correct Data')]),
        ),
    ]
