# Generated by Django 2.1.2 on 2019-06-21 10:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20190621_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenth',
            name='full_mark',
            field=models.IntegerField(validators=[django.core.validators.RegexValidator('^[0-9]{4}$', message='Please Enter Correct Data')]),
        ),
        migrations.AlterField(
            model_name='tenth',
            name='secured_mark',
            field=models.IntegerField(validators=[django.core.validators.RegexValidator('^[0-9]{4}$', message='Please Enter Correct Data')]),
        ),
    ]
