# Generated by Django 2.1.2 on 2019-07-17 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20190717_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='student_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student'),
        ),
    ]
