# Generated by Django 2.1.2 on 2019-06-21 10:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20190621_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.CharField(max_length=20)),
                ('stream', models.CharField(max_length=20)),
                ('school', models.CharField(max_length=20)),
                ('university', models.CharField(max_length=20)),
                ('full_mark', models.IntegerField(validators=[django.core.validators.RegexValidator('^[0-9]{4}$', message='Please Enter Correct Data')])),
                ('secured_mark', models.IntegerField(validators=[django.core.validators.RegexValidator('^[0-9]{4}$', message='Please Enter Correct Data')])),
                ('percentage', models.FloatField(max_length=4, verbose_name='percentage')),
            ],
        ),
        migrations.CreateModel(
            name='PostDegree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.CharField(max_length=20)),
                ('stream', models.CharField(max_length=20)),
                ('school', models.CharField(max_length=20)),
                ('university', models.CharField(max_length=20)),
                ('full_mark', models.IntegerField(validators=[django.core.validators.RegexValidator('^[0-9]{4}$', message='Please Enter Correct Data')])),
                ('secured_mark', models.IntegerField(validators=[django.core.validators.RegexValidator('^[0-9]{4}$', message='Please Enter Correct Data')])),
                ('percentage', models.FloatField(max_length=4, verbose_name='percentage')),
            ],
        ),
        migrations.CreateModel(
            name='Twelth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.CharField(max_length=20)),
                ('stream', models.CharField(max_length=20)),
                ('school', models.CharField(max_length=20)),
                ('university', models.CharField(max_length=20)),
                ('full_mark', models.IntegerField(validators=[django.core.validators.RegexValidator('^[0-9]{4}$', message='Please Enter Correct Data')])),
                ('secured_mark', models.IntegerField(validators=[django.core.validators.RegexValidator('^[0-9]{4}$', message='Please Enter Correct Data')])),
                ('percentage', models.FloatField(max_length=4, verbose_name='percentage')),
            ],
        ),
        migrations.AddField(
            model_name='saf',
            name='tenth',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.Tenth'),
        ),
        migrations.AddField(
            model_name='saf',
            name='degree',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.Degree'),
        ),
        migrations.AddField(
            model_name='saf',
            name='post_degree',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.PostDegree'),
        ),
        migrations.AddField(
            model_name='saf',
            name='twelth',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.Twelth'),
        ),
    ]
