# Generated by Django 2.1.2 on 2019-06-21 12:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20190621_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttachmentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_pic', models.ImageField(upload_to='images/')),
                ('tenth', models.ImageField(upload_to='tenth/')),
                ('twelth', models.ImageField(upload_to='twelth/')),
                ('degree', models.ImageField(blank=True, upload_to='degree/')),
                ('clc', models.ImageField(blank=True, upload_to='clc/')),
                ('conduct_certificate', models.ImageField(blank=True, upload_to='conduct/')),
                ('migration', models.ImageField(blank=True, upload_to='migration/')),
                ('birth_certificate', models.ImageField(blank=True, upload_to='birth/')),
                ('address', models.ImageField(blank=True, upload_to='address/')),
                ('thumb', models.ImageField(blank=True, upload_to='thumb/')),
                ('signature', models.ImageField(blank=True, upload_to='signatures/')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Districts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Entrance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('year', models.IntegerField(choices=[(1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019)], default=2019, verbose_name='year')),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PermanentAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_plot_no', models.TextField()),
                ('Lane', models.TextField()),
                ('pin', models.IntegerField(validators=[django.core.validators.RegexValidator('^[0-9]{6}$', message='')])),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Country')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Districts')),
            ],
        ),
        migrations.CreateModel(
            name='PresentAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_plot_no', models.TextField()),
                ('Lane', models.TextField()),
                ('pin', models.IntegerField(validators=[django.core.validators.RegexValidator('^[0-9]{6}$', message='')])),
                ('same_address', models.BooleanField(default=False)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Country')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Districts')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=30)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.Country')),
            ],
        ),
        migrations.CreateModel(
            name='StudentApplicationForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateTimeField(auto_now_add=True)),
                ('admission_no', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[0-9]{10}$', message='Please Enter Correct Data')])),
                ('admission_date', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Branch')),
                ('degree', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.Degree')),
                ('entrances', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Entrance')),
                ('images', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.AttachmentDetails')),
                ('parent_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.ParentDetails')),
                ('permanent_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.PermanentAddress')),
                ('post_degree', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.PostDegree')),
                ('present_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.PresentAddress')),
                ('student_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.StudentDetail')),
                ('tenth', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.Tenth')),
                ('twelth', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.Twelth')),
            ],
        ),
        migrations.RemoveField(
            model_name='saf',
            name='course',
        ),
        migrations.RemoveField(
            model_name='saf',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='saf',
            name='parent_details',
        ),
        migrations.RemoveField(
            model_name='saf',
            name='post_degree',
        ),
        migrations.RemoveField(
            model_name='saf',
            name='student_detail',
        ),
        migrations.RemoveField(
            model_name='saf',
            name='tenth',
        ),
        migrations.RemoveField(
            model_name='saf',
            name='twelth',
        ),
        migrations.DeleteModel(
            name='SAF',
        ),
        migrations.AddField(
            model_name='presentaddress',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.State'),
        ),
        migrations.AddField(
            model_name='permanentaddress',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.State'),
        ),
        migrations.AddField(
            model_name='districts',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.State'),
        ),
    ]
