# Generated by Django 2.1.2 on 2019-06-24 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_auto_20190621_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentdetails',
            name='fathers_occupation',
            field=models.CharField(choices=[('GE', 'Govt. Employee'), ('PE', 'Private Employee'), ('SE', 'Self Employed'), ('B', 'Businessman'), ('O', 'Others')], default='Others', max_length=30),
        ),
        migrations.AlterField(
            model_name='parentdetails',
            name='mothers_occupation',
            field=models.CharField(choices=[('GE', 'Govt. Employee'), ('PE', 'Private Employee'), ('SE', 'Self Employed'), ('B', 'Businesswoman'), ('HM', 'Home Maker'), ('O', 'Others')], default='Others', max_length=30),
        ),
    ]
