# Generated by Django 2.1.2 on 2019-06-24 05:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_auto_20190624_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenth',
            name='full_mark',
            field=models.FloatField(validators=[django.core.validators.RegexValidator('^[0-9]{4}$', message='Please Enter Correct Data')]),
        ),
        migrations.AlterField(
            model_name='tenth',
            name='secured_mark',
            field=models.FloatField(validators=[django.core.validators.RegexValidator('^[0-9]{4}$', message='Please Enter Correct Data')]),
        ),
    ]
