# Generated by Django 2.1.2 on 2019-06-24 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_auto_20190624_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenth',
            name='full_mark',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tenth',
            name='secured_mark',
            field=models.IntegerField(),
        ),
    ]
