# Generated by Django 2.1.2 on 2019-06-24 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_auto_20190624_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degree',
            name='full_mark',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='degree',
            name='secured_mark',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='postdegree',
            name='full_mark',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='postdegree',
            name='secured_mark',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='twelth',
            name='full_mark',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='twelth',
            name='secured_mark',
            field=models.IntegerField(),
        ),
    ]
