# Generated by Django 2.1.2 on 2019-06-24 11:30

from django.db import migrations, models
import student.models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_auto_20190624_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachmentdetails',
            name='student_pic',
        ),
        migrations.AddField(
            model_name='attachmentdetails',
            name='student_image',
            field=models.ImageField(default='my-upload4.jpg', upload_to=student.models.PathAndRename('attachments/2019/06/24')),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attachmentdetails',
            name='address',
            field=models.ImageField(upload_to=student.models.PathAndRename('attachments/2019/06/24')),
        ),
        migrations.AlterField(
            model_name='attachmentdetails',
            name='birth_certificate',
            field=models.ImageField(upload_to=student.models.PathAndRename('attachments/2019/06/24')),
        ),
        migrations.AlterField(
            model_name='attachmentdetails',
            name='clc',
            field=models.ImageField(upload_to=student.models.PathAndRename('attachments/2019/06/24')),
        ),
        migrations.AlterField(
            model_name='attachmentdetails',
            name='conduct_certificate',
            field=models.ImageField(upload_to=student.models.PathAndRename('attachments/2019/06/24')),
        ),
        migrations.AlterField(
            model_name='attachmentdetails',
            name='degree',
            field=models.ImageField(upload_to=student.models.PathAndRename('attachments/2019/06/24')),
        ),
        migrations.AlterField(
            model_name='attachmentdetails',
            name='migration',
            field=models.ImageField(upload_to=student.models.PathAndRename('attachments/2019/06/24')),
        ),
        migrations.AlterField(
            model_name='attachmentdetails',
            name='signature',
            field=models.ImageField(upload_to=student.models.PathAndRename('attachments/2019/06/24')),
        ),
        migrations.AlterField(
            model_name='attachmentdetails',
            name='tenth',
            field=models.ImageField(upload_to=student.models.PathAndRename('attachments/2019/06/24')),
        ),
        migrations.AlterField(
            model_name='attachmentdetails',
            name='thumb',
            field=models.ImageField(upload_to=student.models.PathAndRename('attachments/2019/06/24')),
        ),
        migrations.AlterField(
            model_name='attachmentdetails',
            name='twelth',
            field=models.ImageField(upload_to=student.models.PathAndRename('attachments/2019/06/24')),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='caste',
            field=models.CharField(choices=[('Gen', 'GEN'), ('SC', 'SC'), ('ST', 'ST'), ('OBC', 'OBC'), ('Others', 'Others')], default='Others', max_length=10),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='sub_caste',
            field=models.CharField(choices=[('Gen', 'GEN'), ('SC', 'SC'), ('ST', 'ST'), ('OBC', 'OBC'), ('Others', 'Others')], default='Others', max_length=10),
        ),
    ]
