# Generated by Django 2.1.2 on 2019-06-25 07:15

from django.db import migrations, models
import student.models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_auto_20190624_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachmentdetails',
            name='address',
            field=models.ImageField(upload_to=student.models.PathAndRename('attachments/2019/06/25')),
        ),
        migrations.AlterField(
            model_name='attachmentdetails',
            name='birth_certificate',
            field=models.ImageField(upload_to=student.models.PathAndRename('attachments/2019/06/25')),
        ),
        migrations.AlterField(
            model_name='attachmentdetails',
            name='clc',
            field=models.ImageField(upload_to=student.models.PathAndRename('attachments/2019/06/25')),
        ),
        migrations.AlterField(
            model_name='attachmentdetails',
            name='conduct_certificate',
            field=models.ImageField(upload_to=student.models.PathAndRename('attachments/2019/06/25')),
        ),
        migrations.AlterField(
            model_name='attachmentdetails',
            name='degree',
            field=models.ImageField(upload_to=student.models.PathAndRename('attachments/2019/06/25')),
        ),
        migrations.AlterField(
            model_name='attachmentdetails',
            name='migration',
            field=models.ImageField(upload_to=student.models.PathAndRename('attachments/2019/06/25')),
        ),
        migrations.AlterField(
            model_name='attachmentdetails',
            name='signature',
            field=models.ImageField(upload_to=student.models.PathAndRename('attachments/2019/06/25')),
        ),
        migrations.AlterField(
            model_name='attachmentdetails',
            name='student_image',
            field=models.ImageField(upload_to=student.models.PathAndRename('attachments/2019/06/25')),
        ),
        migrations.AlterField(
            model_name='attachmentdetails',
            name='tenth',
            field=models.ImageField(upload_to=student.models.PathAndRename('attachments/2019/06/25')),
        ),
        migrations.AlterField(
            model_name='attachmentdetails',
            name='thumb',
            field=models.ImageField(upload_to=student.models.PathAndRename('attachments/2019/06/25')),
        ),
        migrations.AlterField(
            model_name='attachmentdetails',
            name='twelth',
            field=models.ImageField(upload_to=student.models.PathAndRename('attachments/2019/06/25')),
        ),
    ]
