# Generated by Django 2.1.2 on 2019-06-26 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0017_auto_20190626_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentapplicationform',
            name='course',
        ),
        migrations.RemoveField(
            model_name='studentapplicationform',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='studentapplicationform',
            name='entrances',
        ),
        migrations.RemoveField(
            model_name='studentapplicationform',
            name='images',
        ),
        migrations.RemoveField(
            model_name='studentapplicationform',
            name='parent_details',
        ),
        migrations.RemoveField(
            model_name='studentapplicationform',
            name='permanent_address',
        ),
        migrations.RemoveField(
            model_name='studentapplicationform',
            name='post_degree',
        ),
        migrations.RemoveField(
            model_name='studentapplicationform',
            name='present_address',
        ),
        migrations.RemoveField(
            model_name='studentapplicationform',
            name='student_detail',
        ),
        migrations.RemoveField(
            model_name='studentapplicationform',
            name='tenth',
        ),
        migrations.RemoveField(
            model_name='studentapplicationform',
            name='twelth',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='address',
            new_name='student_address',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='birth_certificate',
            new_name='student_birth_certificate',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='clc',
            new_name='student_clc',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='conduct_certificate',
            new_name='student_conduct_certificate',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='degree',
            new_name='student_degree',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='migration',
            new_name='student_migration',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='signature',
            new_name='student_pic',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student_image',
            new_name='student_signature',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='tenth',
            new_name='student_tenth',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='thumb',
            new_name='student_thumb',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='twelth',
            new_name='student_twelth',
        ),
        migrations.DeleteModel(
            name='StudentApplicationForm',
        ),
    ]
