# Generated by Django 2.1.2 on 2019-06-26 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0018_auto_20190626_1405'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Degree',
        ),
        migrations.DeleteModel(
            name='Entrance',
        ),
        migrations.DeleteModel(
            name='ParentDetails',
        ),
        migrations.RemoveField(
            model_name='permanentaddress',
            name='country',
        ),
        migrations.RemoveField(
            model_name='permanentaddress',
            name='district',
        ),
        migrations.RemoveField(
            model_name='permanentaddress',
            name='state',
        ),
        migrations.DeleteModel(
            name='PostDegree',
        ),
        migrations.RemoveField(
            model_name='presentaddress',
            name='country',
        ),
        migrations.RemoveField(
            model_name='presentaddress',
            name='district',
        ),
        migrations.RemoveField(
            model_name='presentaddress',
            name='state',
        ),
        migrations.DeleteModel(
            name='StudentDetail',
        ),
        migrations.DeleteModel(
            name='Tenth',
        ),
        migrations.DeleteModel(
            name='Twelth',
        ),
        migrations.AddField(
            model_name='student',
            name='nationality',
            field=models.CharField(choices=[('india', 'India'), ('others', 'others')], default='india', max_length=10),
        ),
        migrations.DeleteModel(
            name='PermanentAddress',
        ),
        migrations.DeleteModel(
            name='PresentAddress',
        ),
    ]
