# Generated by Django 2.1.2 on 2019-06-26 12:49

from django.db import migrations, models
import student.models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0020_remove_student_twelth_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='degree_marksheet',
            field=models.ImageField(blank=True, upload_to=student.models.PathAndRename('documents/2019/06/26')),
        ),
        migrations.AddField(
            model_name='student',
            name='tenth_marksheet',
            field=models.ImageField(blank=True, upload_to=student.models.PathAndRename('documents/2019/06/26')),
        ),
        migrations.AddField(
            model_name='student',
            name='tewlth_marksheet',
            field=models.ImageField(blank=True, upload_to=student.models.PathAndRename('documents/2019/06/26')),
        ),
        migrations.AlterField(
            model_name='student',
            name='permanent_Lane',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='student',
            name='permanent_house_plot_no',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='student',
            name='present_Lane',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='student',
            name='present_house_plot_no',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_address',
            field=models.ImageField(blank=True, upload_to=student.models.PathAndRename('documents/2019/06/26')),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_birth_certificate',
            field=models.ImageField(blank=True, upload_to=student.models.PathAndRename('documents/2019/06/26')),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_clc',
            field=models.ImageField(blank=True, upload_to=student.models.PathAndRename('documents/2019/06/26')),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_conduct_certificate',
            field=models.ImageField(blank=True, upload_to=student.models.PathAndRename('documents/2019/06/26')),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_degree',
            field=models.ImageField(blank=True, upload_to=student.models.PathAndRename('documents/2019/06/26')),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_migration',
            field=models.ImageField(blank=True, upload_to=student.models.PathAndRename('documents/2019/06/26')),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_pic',
            field=models.ImageField(blank=True, upload_to=student.models.PathAndRename('documents/2019/06/26')),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_signature',
            field=models.ImageField(blank=True, upload_to=student.models.PathAndRename('documents/2019/06/26')),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_tenth',
            field=models.ImageField(blank=True, upload_to=student.models.PathAndRename('documents/2019/06/26')),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_thumb',
            field=models.ImageField(blank=True, upload_to=student.models.PathAndRename('documents/2019/06/26')),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_twelth',
            field=models.ImageField(blank=True, upload_to=student.models.PathAndRename('documents/2019/06/26')),
        ),
    ]
