# Generated by Django 2.1.2 on 2019-06-26 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0021_auto_20190626_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='term_and_condition',
            field=models.BooleanField(default=False),
        ),
    ]
