# Generated by Django 2.1.2 on 2019-06-28 10:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0025_auto_20190628_1438'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='communication_address_lane',
            new_name='communication_lane_address',
        ),
        migrations.AlterField(
            model_name='employee',
            name='pin',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator('^[0-9]{6}$', message='')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='permanent_pin',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^[0-9]{6}$', message='Aadhar Number must be of 12 Digits')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='present_pin',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^[0-9]{6}$', message='Aadhar Number must be of 12 Digits')]),
        ),
    ]
