# Generated by Django 2.1.2 on 2019-06-28 10:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0026_auto_20190628_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator('^[0-9]{30}$', message='Enter Bank Account Number in Digits')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pin',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^[0-9]{6}$', message='')]),
        ),
    ]
