# Generated by Django 2.1.2 on 2019-06-28 10:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0027_auto_20190628_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='aadhar_no',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator('^[0-9]{12}$', message='Aadhar Number must be of 12 Digits')]),
        ),
    ]
