# Generated by Django 2.1.2 on 2019-06-28 10:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0028_auto_20190628_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='industry_experience',
            field=models.IntegerField(max_length=2, validators=[django.core.validators.RegexValidator('^[0-9]{2}$', message='')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='teaching_experience',
            field=models.CharField(max_length=2, validators=[django.core.validators.RegexValidator('^[0-9]{2}$', message='')]),
        ),
    ]
