# Generated by Django 2.1.2 on 2019-06-28 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0029_auto_20190628_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='bank_account_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='industry_experience',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='no_of_pg_projects',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='patents_issued',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='teaching_experience',
            field=models.IntegerField(),
        ),
    ]
