# Generated by Django 2.1.2 on 2019-06-28 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0030_auto_20190628_1557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='permanent_house_plot_no',
            new_name='permanent_house_no',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='present_house_plot_no',
            new_name='present_house_no',
        ),
    ]
