# Generated by Django 2.1.2 on 2019-06-28 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0031_auto_20190628_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='present_same_address',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
