# Generated by Django 2.1.2 on 2019-06-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0032_auto_20190628_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='communication_lane_address',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='employee',
            name='landmark',
            field=models.CharField(max_length=70),
        ),
    ]
