# Generated by Django 2.1.2 on 2019-06-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0033_auto_20190628_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(default='xyz@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
