# Generated by Django 2.1.2 on 2019-06-28 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0034_employee_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
