# Generated by Django 2.1.2 on 2019-07-02 07:38

from django.db import migrations, models
import student.models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0036_auto_20190629_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachmentdetails',
            name='address',
            field=models.ImageField(upload_to=student.models.PathAndRename('attachments/2019/07/02')),
        ),
        migrations.AlterField(
            model_name='attachmentdetails',
            name='birth_certificate',
            field=models.ImageField(upload_to=student.models.PathAndRename('attachments/2019/07/02')),
        ),
        migrations.AlterField(
            model_name='attachmentdetails',
            name='clc',
            field=models.ImageField(upload_to=student.models.PathAndRename('attachments/2019/07/02')),
        ),
        migrations.AlterField(
            model_name='attachmentdetails',
            name='conduct_certificate',
            field=models.ImageField(upload_to=student.models.PathAndRename('attachments/2019/07/02')),
        ),
        migrations.AlterField(
            model_name='attachmentdetails',
            name='degree',
            field=models.ImageField(upload_to=student.models.PathAndRename('attachments/2019/07/02')),
        ),
        migrations.AlterField(
            model_name='attachmentdetails',
            name='migration',
            field=models.ImageField(upload_to=student.models.PathAndRename('attachments/2019/07/02')),
        ),
        migrations.AlterField(
            model_name='attachmentdetails',
            name='signature',
            field=models.ImageField(upload_to=student.models.PathAndRename('attachments/2019/07/02')),
        ),
        migrations.AlterField(
            model_name='attachmentdetails',
            name='student_image',
            field=models.ImageField(upload_to=student.models.PathAndRename('attachments/2019/07/02')),
        ),
        migrations.AlterField(
            model_name='attachmentdetails',
            name='tenth',
            field=models.ImageField(upload_to=student.models.PathAndRename('attachments/2019/07/02')),
        ),
        migrations.AlterField(
            model_name='attachmentdetails',
            name='thumb',
            field=models.ImageField(upload_to=student.models.PathAndRename('attachments/2019/07/02')),
        ),
        migrations.AlterField(
            model_name='attachmentdetails',
            name='twelth',
            field=models.ImageField(upload_to=student.models.PathAndRename('attachments/2019/07/02')),
        ),
        migrations.AlterField(
            model_name='student',
            name='degree_marksheet',
            field=models.ImageField(blank=True, upload_to=student.models.PathAndRename('documents/2019/07/02')),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_address',
            field=models.ImageField(blank=True, upload_to=student.models.PathAndRename('documents/2019/07/02')),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_birth_certificate',
            field=models.ImageField(blank=True, upload_to=student.models.PathAndRename('documents/2019/07/02')),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_clc',
            field=models.ImageField(blank=True, upload_to=student.models.PathAndRename('documents/2019/07/02')),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_conduct_certificate',
            field=models.ImageField(blank=True, upload_to=student.models.PathAndRename('documents/2019/07/02')),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_degree',
            field=models.ImageField(blank=True, upload_to=student.models.PathAndRename('documents/2019/07/02')),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_migration',
            field=models.ImageField(blank=True, upload_to=student.models.PathAndRename('documents/2019/07/02')),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_pic',
            field=models.ImageField(blank=True, upload_to=student.models.PathAndRename('documents/2019/07/02')),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_signature',
            field=models.ImageField(blank=True, upload_to=student.models.PathAndRename('documents/2019/07/02')),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_tenth',
            field=models.ImageField(blank=True, upload_to=student.models.PathAndRename('documents/2019/07/02')),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_thumb',
            field=models.ImageField(blank=True, upload_to=student.models.PathAndRename('documents/2019/07/02')),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_twelth',
            field=models.ImageField(blank=True, upload_to=student.models.PathAndRename('documents/2019/07/02')),
        ),
        migrations.AlterField(
            model_name='student',
            name='tenth_marksheet',
            field=models.ImageField(blank=True, upload_to=student.models.PathAndRename('documents/2019/07/02')),
        ),
        migrations.AlterField(
            model_name='student',
            name='tewlth_marksheet',
            field=models.ImageField(blank=True, upload_to=student.models.PathAndRename('documents/2019/07/02')),
        ),
    ]
