# Generated by Django 2.1.2 on 2019-07-16 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coursemanagement', '0012_feesmanagementsetting_stream'),
        ('student', '0004_auto_20190716_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeesPlanManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursemanagement.Batch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursemanagement.Course')),
                ('enrollment_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Enrollment')),
                ('fees_plan', models.ManyToManyField(to='coursemanagement.FeesManagementSetting')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursemanagement.Stream')),
            ],
        ),
        migrations.CreateModel(
            name='FeeTypeSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('aprroved_amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('no_of_installments', models.IntegerField()),
                ('next_due_date', models.DateField()),
                ('fee_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursemanagement.Feestype')),
            ],
        ),
    ]
