# Generated by Django 2.1.2 on 2019-07-16 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20190716_1103'),
        ('feemanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feetypesetting',
            name='enrollment_number',
            field=models.ForeignKey(default=124542, on_delete=django.db.models.deletion.CASCADE, to='student.Enrollment'),
            preserve_default=False,
        ),
    ]
