# Generated by Django 2.1.2 on 2019-07-16 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coursemanagement', '0012_feesmanagementsetting_stream'),
        ('feemanagement', '0002_feetypesetting_enrollment_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feetype', models.CharField(max_length=30)),
                ('actual_fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('approved_fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursemanagement.Batch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursemanagement.Course')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursemanagement.Stream')),
            ],
        ),
    ]
